// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pkg/proto/checkout.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckoutStatus int32

const (
	CheckoutStatus_CHECKOUT_STATUS_INITIATED          CheckoutStatus = 0
	CheckoutStatus_CHECKOUT_STATUS_INVENTORY_RESERVED CheckoutStatus = 1
	CheckoutStatus_CHECKOUT_STATUS_PAYMENT_PENDING    CheckoutStatus = 2
	CheckoutStatus_CHECKOUT_STATUS_PAYMENT_COMPLETED  CheckoutStatus = 3
	CheckoutStatus_CHECKOUT_STATUS_COMPLETED          CheckoutStatus = 4
	CheckoutStatus_CHECKOUT_STATUS_FAILED             CheckoutStatus = 5
)

// Enum value maps for CheckoutStatus.
var (
	CheckoutStatus_name = map[int32]string{
		0: "CHECKOUT_STATUS_INITIATED",
		1: "CHECKOUT_STATUS_INVENTORY_RESERVED",
		2: "CHECKOUT_STATUS_PAYMENT_PENDING",
		3: "CHECKOUT_STATUS_PAYMENT_COMPLETED",
		4: "CHECKOUT_STATUS_COMPLETED",
		5: "CHECKOUT_STATUS_FAILED",
	}
	CheckoutStatus_value = map[string]int32{
		"CHECKOUT_STATUS_INITIATED":          0,
		"CHECKOUT_STATUS_INVENTORY_RESERVED": 1,
		"CHECKOUT_STATUS_PAYMENT_PENDING":    2,
		"CHECKOUT_STATUS_PAYMENT_COMPLETED":  3,
		"CHECKOUT_STATUS_COMPLETED":          4,
		"CHECKOUT_STATUS_FAILED":             5,
	}
)

func (x CheckoutStatus) Enum() *CheckoutStatus {
	p := new(CheckoutStatus)
	*p = x
	return p
}

func (x CheckoutStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CheckoutStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_checkout_proto_enumTypes[0].Descriptor()
}

func (CheckoutStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_checkout_proto_enumTypes[0]
}

func (x CheckoutStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CheckoutStatus.Descriptor instead.
func (CheckoutStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_checkout_proto_rawDescGZIP(), []int{0}
}

type InitiateCheckoutRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InitiateCheckoutRequest) Reset() {
	*x = InitiateCheckoutRequest{}
	mi := &file_pkg_proto_checkout_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCheckoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCheckoutRequest) ProtoMessage() {}

func (x *InitiateCheckoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_checkout_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCheckoutRequest.ProtoReflect.Descriptor instead.
func (*InitiateCheckoutRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_checkout_proto_rawDescGZIP(), []int{0}
}

func (x *InitiateCheckoutRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *InitiateCheckoutRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type InitiateCheckoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutId    string                 `protobuf:"bytes,1,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	Status        CheckoutStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=checkout.CheckoutStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateCheckoutResponse) Reset() {
	*x = InitiateCheckoutResponse{}
	mi := &file_pkg_proto_checkout_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateCheckoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateCheckoutResponse) ProtoMessage() {}

func (x *InitiateCheckoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_checkout_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateCheckoutResponse.ProtoReflect.Descriptor instead.
func (*InitiateCheckoutResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_checkout_proto_rawDescGZIP(), []int{1}
}

func (x *InitiateCheckoutResponse) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *InitiateCheckoutResponse) GetStatus() CheckoutStatus {
	if x != nil {
		return x.Status
	}
	return CheckoutStatus_CHECKOUT_STATUS_INITIATED
}

var File_pkg_proto_checkout_proto protoreflect.FileDescriptor

const file_pkg_proto_checkout_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/proto/checkout.proto\x12\bcheckout\"[\n" +
	"\x17InitiateCheckoutRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\"m\n" +
	"\x18InitiateCheckoutResponse\x12\x1f\n" +
	"\vcheckout_id\x18\x01 \x01(\tR\n" +
	"checkoutId\x120\n" +
	"\x06status\x18\x02 \x01(\x0e2\x18.checkout.CheckoutStatusR\x06status*\xde\x01\n" +
	"\x0eCheckoutStatus\x12\x1d\n" +
	"\x19CHECKOUT_STATUS_INITIATED\x10\x00\x12&\n" +
	"\"CHECKOUT_STATUS_INVENTORY_RESERVED\x10\x01\x12#\n" +
	"\x1fCHECKOUT_STATUS_PAYMENT_PENDING\x10\x02\x12%\n" +
	"!CHECKOUT_STATUS_PAYMENT_COMPLETED\x10\x03\x12\x1d\n" +
	"\x19CHECKOUT_STATUS_COMPLETED\x10\x04\x12\x1a\n" +
	"\x16CHECKOUT_STATUS_FAILED\x10\x052l\n" +
	"\x0fCheckoutService\x12Y\n" +
	"\x10InitiateCheckout\x12!.checkout.InitiateCheckoutRequest\x1a\".checkout.InitiateCheckoutResponseB4Z2github.com/fjod/go_cart/checkout-service/pkg/protob\x06proto3"

var (
	file_pkg_proto_checkout_proto_rawDescOnce sync.Once
	file_pkg_proto_checkout_proto_rawDescData []byte
)

func file_pkg_proto_checkout_proto_rawDescGZIP() []byte {
	file_pkg_proto_checkout_proto_rawDescOnce.Do(func() {
		file_pkg_proto_checkout_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_checkout_proto_rawDesc), len(file_pkg_proto_checkout_proto_rawDesc)))
	})
	return file_pkg_proto_checkout_proto_rawDescData
}

var file_pkg_proto_checkout_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_proto_checkout_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_checkout_proto_goTypes = []any{
	(CheckoutStatus)(0),              // 0: checkout.CheckoutStatus
	(*InitiateCheckoutRequest)(nil),  // 1: checkout.InitiateCheckoutRequest
	(*InitiateCheckoutResponse)(nil), // 2: checkout.InitiateCheckoutResponse
}
var file_pkg_proto_checkout_proto_depIdxs = []int32{
	0, // 0: checkout.InitiateCheckoutResponse.status:type_name -> checkout.CheckoutStatus
	1, // 1: checkout.CheckoutService.InitiateCheckout:input_type -> checkout.InitiateCheckoutRequest
	2, // 2: checkout.CheckoutService.InitiateCheckout:output_type -> checkout.InitiateCheckoutResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_proto_checkout_proto_init() }
func file_pkg_proto_checkout_proto_init() {
	if File_pkg_proto_checkout_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_checkout_proto_rawDesc), len(file_pkg_proto_checkout_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_checkout_proto_goTypes,
		DependencyIndexes: file_pkg_proto_checkout_proto_depIdxs,
		EnumInfos:         file_pkg_proto_checkout_proto_enumTypes,
		MessageInfos:      file_pkg_proto_checkout_proto_msgTypes,
	}.Build()
	File_pkg_proto_checkout_proto = out.File
	file_pkg_proto_checkout_proto_goTypes = nil
	file_pkg_proto_checkout_proto_depIdxs = nil
}
