// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pkg/proto/payment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChargeStatus int32

const (
	ChargeStatus_CHARGE_STATUS_SUCCESS ChargeStatus = 0
	ChargeStatus_CHARGE_STATUS_FAILED  ChargeStatus = 1
)

// Enum value maps for ChargeStatus.
var (
	ChargeStatus_name = map[int32]string{
		0: "CHARGE_STATUS_SUCCESS",
		1: "CHARGE_STATUS_FAILED",
	}
	ChargeStatus_value = map[string]int32{
		"CHARGE_STATUS_SUCCESS": 0,
		"CHARGE_STATUS_FAILED":  1,
	}
)

func (x ChargeStatus) Enum() *ChargeStatus {
	p := new(ChargeStatus)
	*p = x
	return p
}

func (x ChargeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChargeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_payment_proto_enumTypes[0].Descriptor()
}

func (ChargeStatus) Type() protoreflect.EnumType {
	return &file_pkg_proto_payment_proto_enumTypes[0]
}

func (x ChargeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChargeStatus.Descriptor instead.
func (ChargeStatus) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_payment_proto_rawDescGZIP(), []int{0}
}

type PaymentRefusal int32

const (
	PaymentRefusal_UNKNOWN       PaymentRefusal = 0
	PaymentRefusal_NO_FUNDS      PaymentRefusal = 1
	PaymentRefusal_CARD_DECLINED PaymentRefusal = 2
	PaymentRefusal_CARD_EXPIRED  PaymentRefusal = 3
	PaymentRefusal_INVALID_CCV   PaymentRefusal = 4
	PaymentRefusal_NETWORK_ERROR PaymentRefusal = 5
)

// Enum value maps for PaymentRefusal.
var (
	PaymentRefusal_name = map[int32]string{
		0: "UNKNOWN",
		1: "NO_FUNDS",
		2: "CARD_DECLINED",
		3: "CARD_EXPIRED",
		4: "INVALID_CCV",
		5: "NETWORK_ERROR",
	}
	PaymentRefusal_value = map[string]int32{
		"UNKNOWN":       0,
		"NO_FUNDS":      1,
		"CARD_DECLINED": 2,
		"CARD_EXPIRED":  3,
		"INVALID_CCV":   4,
		"NETWORK_ERROR": 5,
	}
)

func (x PaymentRefusal) Enum() *PaymentRefusal {
	p := new(PaymentRefusal)
	*p = x
	return p
}

func (x PaymentRefusal) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentRefusal) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_proto_payment_proto_enumTypes[1].Descriptor()
}

func (PaymentRefusal) Type() protoreflect.EnumType {
	return &file_pkg_proto_payment_proto_enumTypes[1]
}

func (x PaymentRefusal) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentRefusal.Descriptor instead.
func (PaymentRefusal) EnumDescriptor() ([]byte, []int) {
	return file_pkg_proto_payment_proto_rawDescGZIP(), []int{1}
}

type ChargeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ChargeStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=payment.ChargeStatus" json:"status,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	// Types that are valid to be assigned to Refusal:
	//
	//	*ChargeResponse_KnownReason
	//	*ChargeResponse_OtherReason
	Refusal       isChargeResponse_Refusal `protobuf_oneof:"refusal"`
	CheckoutId    string                   `protobuf:"bytes,5,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	ReservationId string                   `protobuf:"bytes,6,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargeResponse) Reset() {
	*x = ChargeResponse{}
	mi := &file_pkg_proto_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeResponse) ProtoMessage() {}

func (x *ChargeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeResponse.ProtoReflect.Descriptor instead.
func (*ChargeResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_payment_proto_rawDescGZIP(), []int{0}
}

func (x *ChargeResponse) GetStatus() ChargeStatus {
	if x != nil {
		return x.Status
	}
	return ChargeStatus_CHARGE_STATUS_SUCCESS
}

func (x *ChargeResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ChargeResponse) GetRefusal() isChargeResponse_Refusal {
	if x != nil {
		return x.Refusal
	}
	return nil
}

func (x *ChargeResponse) GetKnownReason() PaymentRefusal {
	if x != nil {
		if x, ok := x.Refusal.(*ChargeResponse_KnownReason); ok {
			return x.KnownReason
		}
	}
	return PaymentRefusal_UNKNOWN
}

func (x *ChargeResponse) GetOtherReason() string {
	if x != nil {
		if x, ok := x.Refusal.(*ChargeResponse_OtherReason); ok {
			return x.OtherReason
		}
	}
	return ""
}

func (x *ChargeResponse) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

func (x *ChargeResponse) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type isChargeResponse_Refusal interface {
	isChargeResponse_Refusal()
}

type ChargeResponse_KnownReason struct {
	KnownReason PaymentRefusal `protobuf:"varint,3,opt,name=known_reason,json=knownReason,proto3,enum=payment.PaymentRefusal,oneof"`
}

type ChargeResponse_OtherReason struct {
	OtherReason string `protobuf:"bytes,4,opt,name=other_reason,json=otherReason,proto3,oneof"` // free-form when enum doesn't fit
}

func (*ChargeResponse_KnownReason) isChargeResponse_Refusal() {}

func (*ChargeResponse_OtherReason) isChargeResponse_Refusal() {}

type ChargeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutId    string                 `protobuf:"bytes,1,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChargeRequest) Reset() {
	*x = ChargeRequest{}
	mi := &file_pkg_proto_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChargeRequest) ProtoMessage() {}

func (x *ChargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChargeRequest.ProtoReflect.Descriptor instead.
func (*ChargeRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_payment_proto_rawDescGZIP(), []int{1}
}

func (x *ChargeRequest) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

type RefundRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CheckoutId    string                 `protobuf:"bytes,1,opt,name=checkout_id,json=checkoutId,proto3" json:"checkout_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_pkg_proto_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_payment_proto_rawDescGZIP(), []int{2}
}

func (x *RefundRequest) GetCheckoutId() string {
	if x != nil {
		return x.CheckoutId
	}
	return ""
}

type RefundResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundResponse) Reset() {
	*x = RefundResponse{}
	mi := &file_pkg_proto_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundResponse) ProtoMessage() {}

func (x *RefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundResponse.ProtoReflect.Descriptor instead.
func (*RefundResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_payment_proto_rawDescGZIP(), []int{3}
}

var File_pkg_proto_payment_proto protoreflect.FileDescriptor

const file_pkg_proto_payment_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/payment.proto\x12\apayment\"\x9c\x02\n" +
	"\x0eChargeResponse\x12-\n" +
	"\x06status\x18\x01 \x01(\x0e2\x15.payment.ChargeStatusR\x06status\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12<\n" +
	"\fknown_reason\x18\x03 \x01(\x0e2\x17.payment.PaymentRefusalH\x00R\vknownReason\x12#\n" +
	"\fother_reason\x18\x04 \x01(\tH\x00R\votherReason\x12\x1f\n" +
	"\vcheckout_id\x18\x05 \x01(\tR\n" +
	"checkoutId\x12%\n" +
	"\x0ereservation_id\x18\x06 \x01(\tR\rreservationIdB\t\n" +
	"\arefusal\"0\n" +
	"\rChargeRequest\x12\x1f\n" +
	"\vcheckout_id\x18\x01 \x01(\tR\n" +
	"checkoutId\"0\n" +
	"\rRefundRequest\x12\x1f\n" +
	"\vcheckout_id\x18\x01 \x01(\tR\n" +
	"checkoutId\"\x10\n" +
	"\x0eRefundResponse*C\n" +
	"\fChargeStatus\x12\x19\n" +
	"\x15CHARGE_STATUS_SUCCESS\x10\x00\x12\x18\n" +
	"\x14CHARGE_STATUS_FAILED\x10\x01*t\n" +
	"\x0ePaymentRefusal\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bNO_FUNDS\x10\x01\x12\x11\n" +
	"\rCARD_DECLINED\x10\x02\x12\x10\n" +
	"\fCARD_EXPIRED\x10\x03\x12\x0f\n" +
	"\vINVALID_CCV\x10\x04\x12\x11\n" +
	"\rNETWORK_ERROR\x10\x052\x86\x01\n" +
	"\x0ePaymentService\x129\n" +
	"\x06Charge\x12\x16.payment.ChargeRequest\x1a\x17.payment.ChargeResponse\x129\n" +
	"\x06Refund\x12\x16.payment.RefundRequest\x1a\x17.payment.RefundResponseB3Z1github.com/fjod/go_cart/payment-service/pkg/protob\x06proto3"

var (
	file_pkg_proto_payment_proto_rawDescOnce sync.Once
	file_pkg_proto_payment_proto_rawDescData []byte
)

func file_pkg_proto_payment_proto_rawDescGZIP() []byte {
	file_pkg_proto_payment_proto_rawDescOnce.Do(func() {
		file_pkg_proto_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_payment_proto_rawDesc), len(file_pkg_proto_payment_proto_rawDesc)))
	})
	return file_pkg_proto_payment_proto_rawDescData
}

var file_pkg_proto_payment_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_proto_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_proto_payment_proto_goTypes = []any{
	(ChargeStatus)(0),      // 0: payment.ChargeStatus
	(PaymentRefusal)(0),    // 1: payment.PaymentRefusal
	(*ChargeResponse)(nil), // 2: payment.ChargeResponse
	(*ChargeRequest)(nil),  // 3: payment.ChargeRequest
	(*RefundRequest)(nil),  // 4: payment.RefundRequest
	(*RefundResponse)(nil), // 5: payment.RefundResponse
}
var file_pkg_proto_payment_proto_depIdxs = []int32{
	0, // 0: payment.ChargeResponse.status:type_name -> payment.ChargeStatus
	1, // 1: payment.ChargeResponse.known_reason:type_name -> payment.PaymentRefusal
	3, // 2: payment.PaymentService.Charge:input_type -> payment.ChargeRequest
	4, // 3: payment.PaymentService.Refund:input_type -> payment.RefundRequest
	2, // 4: payment.PaymentService.Charge:output_type -> payment.ChargeResponse
	5, // 5: payment.PaymentService.Refund:output_type -> payment.RefundResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_payment_proto_init() }
func file_pkg_proto_payment_proto_init() {
	if File_pkg_proto_payment_proto != nil {
		return
	}
	file_pkg_proto_payment_proto_msgTypes[0].OneofWrappers = []any{
		(*ChargeResponse_KnownReason)(nil),
		(*ChargeResponse_OtherReason)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_payment_proto_rawDesc), len(file_pkg_proto_payment_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_payment_proto_goTypes,
		DependencyIndexes: file_pkg_proto_payment_proto_depIdxs,
		EnumInfos:         file_pkg_proto_payment_proto_enumTypes,
		MessageInfos:      file_pkg_proto_payment_proto_msgTypes,
	}.Build()
	File_pkg_proto_payment_proto = out.File
	file_pkg_proto_payment_proto_goTypes = nil
	file_pkg_proto_payment_proto_depIdxs = nil
}
