// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pkg/proto/cart.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AddCartItemService_AddItem_FullMethodName = "/cart.AddCartItemService/AddItem"
)

// AddCartItemServiceClient is the client API for AddCartItemService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AddCartItem service definition
type AddCartItemServiceClient interface {
	AddItem(ctx context.Context, in *AddCartItemRequest, opts ...grpc.CallOption) (*AddCartItemResponse, error)
}

type addCartItemServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAddCartItemServiceClient(cc grpc.ClientConnInterface) AddCartItemServiceClient {
	return &addCartItemServiceClient{cc}
}

func (c *addCartItemServiceClient) AddItem(ctx context.Context, in *AddCartItemRequest, opts ...grpc.CallOption) (*AddCartItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddCartItemResponse)
	err := c.cc.Invoke(ctx, AddCartItemService_AddItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddCartItemServiceServer is the server API for AddCartItemService service.
// All implementations must embed UnimplementedAddCartItemServiceServer
// for forward compatibility.
//
// AddCartItem service definition
type AddCartItemServiceServer interface {
	AddItem(context.Context, *AddCartItemRequest) (*AddCartItemResponse, error)
	mustEmbedUnimplementedAddCartItemServiceServer()
}

// UnimplementedAddCartItemServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAddCartItemServiceServer struct{}

func (UnimplementedAddCartItemServiceServer) AddItem(context.Context, *AddCartItemRequest) (*AddCartItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddItem not implemented")
}
func (UnimplementedAddCartItemServiceServer) mustEmbedUnimplementedAddCartItemServiceServer() {}
func (UnimplementedAddCartItemServiceServer) testEmbeddedByValue()                            {}

// UnsafeAddCartItemServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddCartItemServiceServer will
// result in compilation errors.
type UnsafeAddCartItemServiceServer interface {
	mustEmbedUnimplementedAddCartItemServiceServer()
}

func RegisterAddCartItemServiceServer(s grpc.ServiceRegistrar, srv AddCartItemServiceServer) {
	// If the following call panics, it indicates UnimplementedAddCartItemServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AddCartItemService_ServiceDesc, srv)
}

func _AddCartItemService_AddItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCartItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddCartItemServiceServer).AddItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AddCartItemService_AddItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddCartItemServiceServer).AddItem(ctx, req.(*AddCartItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AddCartItemService_ServiceDesc is the grpc.ServiceDesc for AddCartItemService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AddCartItemService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cart.AddCartItemService",
	HandlerType: (*AddCartItemServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddItem",
			Handler:    _AddCartItemService_AddItem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/proto/cart.proto",
}
